### ISSUE TITLE
Consider Purple Air and Fire icon collapsable marker group to allow for clicking all available icons

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/alaska-wildfires#110]
Currently, with the large number of Purple Air sensors in Fairbanks and / or when the fires pile on top of one another in the map, there isn't a good way to access the icons below the top level icon. Consider a way to group these markers and give an "average" AQI or "total" acres burning as the icon until it's clicked?

<img width="749" alt="Screenshot 2024-06-27 at 10 08 15 AM" src="https://github.com/ua-snap/alaska-wildfires/assets/563260/1d6cc1f4-9b8c-4437-ae2e-2cd3a7ebbe60">

**Comment by brucecrevensten** [comment]
It is true and valid.  I'm also unsure how to proceed: as-is, it works pretty OK with a "overall color pattern" but agreed that the numbers become unreadable in particular.  Without increasing zoom level I don't know what to change.  Clustering wouldn't be effective because zoomed-out it would have one number for the whole area which isn't great; this really is showing some meaningful detail.  Almost like the individual points are "pixels".

**Comment by brucecrevensten** [comment]
I'm going to close this because we haven't gotten direct feedback around this and clustering would hide important info.
